### ISSUE TITLE
Error Name

### ISSUE THREAD

**Issue by lccodes** [GJWT/javaOIDCMsgForCOMMENTS#6]
https://github.com/GJWT/javaOIDCMsg/blob/cbdf7aa5be7896a7958e55b2ac2dda0a0956adda/lib/src/test/java/com/auth0/jwt/JWTTest.java#L73

Can you make this error a bit more professional and descriptive?

**Comment by lccodes** [comment]
That was meant to tag line 72

**Comment by jdahmubed** [comment]
fixed on my end
